//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SolveIt.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_GL_VIEW                     101
#define IDD_CURRENTLOOP                 102
#define IDR_GLVIEW_TMPL                 103
#define ID_TextBoxWindow                104
#define IDR_MAINFRAME                   128
#define IDR_EXAMPLES_MENU               129
#define IDR_SOLVEITYPE                  130

#define IDD_SolveItVIEW                 131
#define IDD_EXAMINEPAIR                 132
#define IDD_WAVENUMBERS                 133
#define IDD_HELPBOX                     134
#define IDD_EXAMINECOLLISIONTIMES       135

#define IDB_TREELIST                    136
#define IDB_TREELIST2                   137
#define IDB_TRASH                       138

#define IDC_CURSOR_SEL                  139
#define IDC_CURSOR_HAND                 140
#define IDM_EXIT                        141
#define IDC_EDIT_pointContact2          142
#define IDC_EDIT_ContactType            143
#define IDC_EDIT_RelativeNormalMotion   144
#define IDC_EDIT_separation             145
#define IDC_EDIT_VelPointContact1       146
#define IDC_EDIT_VelPointContact2       147
#define IDC_EDIT_normal                 148
#define IDC_EDIT_pointContact1          149
#define IDD_CHANGECHARGE                150
#define IDC_EDIT_CHARGE                 151
#define IDR_MENU_FieldDisplay           152

#define IDI_GLTEST                      153
#define IDI_SMALL                       154
#define IDC_GLTEST                      155
#define IDI_ICON1                       156

#define IDC_RUN                         1000
#define IDC_STOP                        1001
#define IDC_CLEAR                       1002
#define IDC_PNG                         1003
#define IDC_EPS                         1004
#define IDC_EPS2                        1005
#define IDC_PRINT_CODE                  1005
#define ID_VIEW_TOGGLE                  1006
#define ID_VIEW_RESET                   1007
#define IDC_BUTTON_Reset                1008
#define ID_VIEW_RESET2                  1009
#define IDC_SINGLE_STEP                 1009
#define ID_VIEW_FLYBY                   1010
#define IDC_HTMLVIEW                    1011
#define IDC_EDIT1                       1012

#define IDC_EDIT_ScanStepsize           1020
#define IDC_EDIT_BEGIN_x                1021
#define IDC_EDIT_BEGIN_y                1022
#define IDC_EDIT_END_x                  1023
#define IDC_EDIT_END_y                  1024
#define IDC_EDIT_ScanTime               1025
#define IDC_BUTTON_Scan                 1026

#define IDC_EDIT_NUMBERWAVENUMBERS      1027
#define IDC_EDIT_RATIO                  1028
#define IDC_EDIT_WAVELENGTH             1029
#define IDC_EDIT_DT                     1030
#define IDC_APPLY                       1031
#define IDB_Psi                         1032
#define IDC_RADIO1                      1033
#define IDC_RADIO2                      1034
#define IDC_RADIO3                      1035
#define IDC_RADIO4                      1036
#define IDC_RADIO5                      1037


#define ID__FIELDLINES                  32770
#define ID_VIEW_1DIM                    32772
#define ID_VIEW_2DIM                    32773
#define ID_VIEW_3DIM                    32774
#define ID_POPUP_COPY                   32775
#define ID_POPUP_CUT                    32776
#define ID_POPUP_CLEAR                  32777
#define ID_POPUP_PASTE                  32778
#define ID__BACKGROUND                  32780
#define ID__VECTORFIELDS                32781
#define ID__EQUIPOTENTIALS              32782
#define ID_electric                     32783
#define ID_magnetic                     32784
#define ID_gravitational                32785

#define ID__clear_VECTORFIELDS                32786
#define ID__clear_EQUIPOTENTIALS              32787
#define ID_clear_electric                     32788
#define ID_clear_magnetic                     32789
#define ID_clear_gravitational                32790

#define ID_POPUP_Test_Plot                     32798
#define ID_POPUP_Test_Recursion                32799
#define ID_POPUP_Spline                 32800
#define ID_POPUP_VECTORALGEBRA_SUM      32801
#define ID_POPUP_VECTORALGEBRA_DIFFERENCE 32802
#define ID_POPUP_VECTORALGEBRA_CROSSPRODUCT 32803
#define ID_POPUP_MECHANICS_MULTIBODY_TEST 32804
#define ID_POPUP_MECHANICS_MULTIBODY_SLIDER 32805
#define ID_POPUP_MECHANICS_MULTIBODY_CHAIN 32806
#define ID_POPUP_MECHANICS_MultiMassSpring 32807
#define ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEINDEPENDENT_XCOMPONENT 32878
#define ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEDEPENDENT_XCOMPONENT 32879
#define ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEINDEPENDENT_YCOMPONENT 32880
#define ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEDEPENDENT_YCOMPONENT 32881
#define ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEINDEPENDENT_ZCOMPONENT 32882
#define ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEDEPENDENT_ZCOMPONENT 32883
#define ID_POPUP_MECHANICS_RAMP         32884
#define ID_POPUP_MECHANICS_TWOBODY      32885
#define ID_POPUP_MECHANICS_BALLONSHPERE 32886
#define ID_POPUP_MECHANICS_PULLEY       32887
#define ID_POPUP_MECHANICS_SPHEREANDBLOCK 32888
#define ID_POPUP_MECHANICS_PULLEYANDTWOBLOCKS 32889
#define ID_POPUP_MECHANICS_BLOCK_AND_PULLEY 32890
#define ID_POPUP_MECHANICS_BLOCKANDTACKLE 32891
#define ID_POPUP_MECHANICS_TEST         32892
#define ID_POPUP_MECHANICS_FOURBODYCOLLISION 32893
#define ID_POPUP_MECHANICS_FOURBODYCOLLISION2 32894
#define ID_POPUP_MECHANICS_LENNARDJONESPOTENTIAL 32895
#define ID_POPUP_MECHANICS_LNNRDJNSPTNTLHEATEDCOOLED 32896
#define ID_POPUP_MECHANICS_INELASTICCOLLISION 32897
#define ID_POPUP_MECHANICS_INELASTICPENDULUMCOLLISION 32898
#define ID_POPUP_MECHANICS_NEWTONSCRADLE 32899
#define ID_POPUP_MECHANICS_NEWTONSCRADLE2 32900
#define ID_POPUP_MECHANICS_THREEBODY    32901
#define ID_POPUP_OSCILLATORS            32902
#define ID_POPUP_OSCILLATORS_SIMPLEHARMONIC 32903
#define ID_POPUP_OSCILLATORS_SIMPLEPENDULUM 32904
#define ID_POPUP_OSCILLATORS_RESONANTSIMPLEHARMONIC 32905
#define ID_POPUP_OSCILLATORS_NONLINEARCUBIC 32906
#define ID_POPUP_OSCILLATORS_ANHARMONIC 32907
#define ID_POPUP_OSCILLATORS_CYCLOTRON  32908
#define ID_POPUP_PROJECTILE_CANNONBALL  32909
#define ID_POPUP_PROJECTILE_THREEBODY   32910
#define ID_POPUP_PROJECTILE_TWOBODY     32911
#define ID_POPUP_GRAVITATION_ORBITALMECHANICS 32912
#define ID_POPUP_GRAVITATION_SUNEARTHMOON 32913
#define ID_POPUP_GRAVITATION_EARTHMOON  32914
#define ID_POPUP_ELECTROMAGNETIC_CYCLOTRON 32915
#define ID_POPUP_ELECTROMAGNETIC_QINUNIFORMCHARGEDSLAB 32916
#define ID_POPUP_ELECTROMAGNETIC_CURRENTLOOP 32917
#define ID_POPUP_ELECTROMAGNETIC_THREEBODY 32918
#define ID_POPUP_ELECTROMAGNETIC_ELECTROSTATICFIELD 32919
#define ID_POPUP_CHAOTIC_TWOBODY        32920
#define ID_POPUP_CHAOTIC_6BODY          32921
#define ID_POPUP_CHAOTIC_TRAPPING       32922
#define ID_POPUP_CHAOTIC_COMPOUNDPENDULUM 32923
#define ID_POPUP_CHAOTIC_PHYSICAL_PENDULUM 32924
#define ID_POPUP_CHAOTIC_CHAIN          32925
#define ID_POPUP_CHAOTIC_PENDULUMANDFIXEDCHARGE 32926
#define ID_POPUP_CHAOTIC_PENDULUMANDPLANARCHARGE 32927
#define ID_POPUP_CHAOTIC_VERHULSTDYNAMICS 32928
#define ID_POPUP_CHAOTIC_RANDOMCHAIN    32929
#define ID_POPUP_CHAOTIC_SUBMERGED      32930
#define ID_POPUP_STATISTICALMECHANICS_NSPHERES 32931
#define ID_POPUP_QUANTUMMECHANICS_SCATTERINGIN2SPATIALDIMENSION 32932
#define ID_POPUP_QUANTUMMECHANICS_SCATTERINGIN1SPATIALDIMENSION 32933
#define ID_POPUP_QUANTUMMECHANICS_SUPERPOSITION 32934
#define ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_PROBLEM214 32935
#define ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_EXAMPLE24 32936
#define ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_PROBLEM237 32937
#define ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_CHAPTER_4 32938
#define ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_CHAPTER_5 32939
#define ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_CHAPTER_6 32940
#define ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_PROBLEM346 32941
#define ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_PROBLEM351 32942
#define ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_PROBLEM360 32943
#define ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_CHAPTER_7_EXAMPLE78 32944
#define ID_POPUP_QUANTUMMECHANICS_Ground_State__IN_1_SPATIALDIMENSION 32963
#define ID_POPUP_QUANTUMMECHANICS_STATIONARY_IN_1_SPATIALDIMENSION 32964
#define ID_POPUP_QUANTUMMECHANICS_STATIONARY_IN_1_SPATIALDIMENSIONB 32965
#define ID_POPUP_QUANTUMMECHANICS_STATIONARY_IN_2_SPATIALDIMENSION 32966
#define ID_POPUP_QUANTUMMECHANICS_Ground_State__BEC 32967

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32968
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           157
#endif
#endif
