// GenExamp.cpp : implementation file
//

#include "stdafx.h"
#include "SolveIt.h"
#include "GenExamp.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CGenExamp

IMPLEMENT_DYNCREATE(CGenExamp, CWinThread)

CGenExamp::CGenExamp()
{
}

CGenExamp::~CGenExamp()
{
}

BOOL CGenExamp::InitInstance()
{
	// TODO:  perform and per-thread initialization here
	return TRUE;
}

int CGenExamp::ExitInstance()
{
	// TODO:  perform any per-thread cleanup here
	return CWinThread::ExitInstance();
}

BEGIN_MESSAGE_MAP(CGenExamp, CWinThread)
	//{{AFX_MSG_MAP(CGenExamp)
		// NOTE - the ClassWizard will add and remove mapping macros here.
	//}}AFX_MSG_MAP
	ON_THREAD_MESSAGE(ID_POPUP_Spline, OnSpline)

	ON_THREAD_MESSAGE(ID_POPUP_VECTORALGEBRA_SUM, OnSum)
	ON_THREAD_MESSAGE(ID_POPUP_VECTORALGEBRA_DIFFERENCE, OnDifference)
	ON_THREAD_MESSAGE(ID_POPUP_VECTORALGEBRA_CROSSPRODUCT, OnCrossProduct)

	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_MULTIBODY_TEST, OnMultiBodyTest)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_MULTIBODY_CHAIN, OnMultiBodyChain)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_MULTIBODY_SLIDER, OnMultiBodySlider)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_MultiMassSpring, OnMultiMassSpring)

	ON_THREAD_MESSAGE(ID_POPUP_OSCILLATORS_SIMPLEPENDULUM, OnSimplePendulum)
	ON_THREAD_MESSAGE(ID_POPUP_OSCILLATORS_SIMPLEHARMONIC, OnSimpleHarmonicOscillator)
	ON_THREAD_MESSAGE(ID_POPUP_ELECTROMAGNETIC_QINUNIFORMCHARGEDSLAB, OnSimpleHarmonicOscillator)
	ON_THREAD_MESSAGE(ID_POPUP_OSCILLATORS_RESONANTSIMPLEHARMONIC, OnResonantSimpleHarmonicOscillator)
	ON_THREAD_MESSAGE(ID_POPUP_OSCILLATORS_NONLINEARCUBIC, OnCubicAnharmonicOscillator)
	ON_THREAD_MESSAGE(ID_POPUP_OSCILLATORS_ANHARMONIC, OnAnharmonicOscillator)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_TEST, OnTest)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_LENNARDJONESPOTENTIAL, OnLennardJones)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_LNNRDJNSPTNTLHEATEDCOOLED, OnLennardJonesHeatedCooled)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_RAMP, OnRamp)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_PULLEY, OnPulley)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_TWOBODY, OnTwoBodyScattering)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_THREEBODY, OnThreeBodyCollision)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_FOURBODYCOLLISION, OnFourBodyCollision)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_FOURBODYCOLLISION2, OnFourBodyCollision2)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_BALLONSHPERE, OnBallOnShpere)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_SPHEREANDBLOCK, OnSphereAndBlock)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_PULLEYANDTWOBLOCKS, OnTwoBlocksAndPulley)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_BLOCK_AND_PULLEY, OnBlockAndPulley)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_BLOCKANDTACKLE, OnBlockAndTackle)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_INELASTICCOLLISION, OnInelasticCollision)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_INELASTICPENDULUMCOLLISION, OnInelasticPendulumCollision)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_NEWTONSCRADLE, OnNewtonCradle)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_NEWTONSCRADLE2, OnNewtonCradle2)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEINDEPENDENT_XCOMPONENT, OnUserDefinedTimeIndependentX)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEINDEPENDENT_YCOMPONENT, OnUserDefinedTimeIndependentY)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEINDEPENDENT_ZCOMPONENT, OnUserDefinedTimeIndependentZ)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEDEPENDENT_XCOMPONENT, OnUserDefinedTimeDependentX)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEDEPENDENT_YCOMPONENT, OnUserDefinedTimeDependentY)
	ON_THREAD_MESSAGE(ID_POPUP_MECHANICS_USERDEFINEDFORCES_TIMEDEPENDENT_ZCOMPONENT, OnUserDefinedTimeDependentZ)

	ON_THREAD_MESSAGE(ID_POPUP_QUANTUMMECHANICS_SCATTERINGIN1SPATIALDIMENSION,  Scattering1Dim)
	ON_THREAD_MESSAGE(ID_POPUP_QUANTUMMECHANICS_SCATTERINGIN2SPATIALDIMENSION,  Scattering2Dim)
	ON_THREAD_MESSAGE(ID_POPUP_QUANTUMMECHANICS_Ground_State__IN_1_SPATIALDIMENSION,  QM_Ground_State_1Dim)
	ON_THREAD_MESSAGE(ID_POPUP_QUANTUMMECHANICS_STATIONARY_IN_1_SPATIALDIMENSION,  QMStationary1Dim)
	ON_THREAD_MESSAGE(ID_POPUP_QUANTUMMECHANICS_STATIONARY_IN_1_SPATIALDIMENSIONB,  QMStationary1DimB)
	ON_THREAD_MESSAGE(ID_POPUP_QUANTUMMECHANICS_STATIONARY_IN_2_SPATIALDIMENSION,  QMStationary2Dim)
	ON_THREAD_MESSAGE(ID_POPUP_QUANTUMMECHANICS_SUPERPOSITION, Superposition)
	ON_THREAD_MESSAGE(ID_POPUP_STATISTICALMECHANICS_NSPHERES, OnN_Body)
	ON_THREAD_MESSAGE(ID_POPUP_GRAVITATION_ORBITALMECHANICS, OnOrbitalMechanics)
	ON_THREAD_MESSAGE(ID_POPUP_GRAVITATION_SUNEARTHMOON, OnSunEarthMoon)
	ON_THREAD_MESSAGE(ID_POPUP_GRAVITATION_EARTHMOON, OnEarthMoon)
	ON_THREAD_MESSAGE(ID_POPUP_PROJECTILE_CANNONBALL, OnCannonBall)
	ON_THREAD_MESSAGE(ID_POPUP_PROJECTILE_TWOBODY, OnTwoBody)
	ON_THREAD_MESSAGE(ID_POPUP_PROJECTILE_THREEBODY, OnThreeBody)
	ON_THREAD_MESSAGE(ID_POPUP_ELECTROMAGNETIC_THREEBODY, OnThreeChargedBodies)
	ON_THREAD_MESSAGE(ID_POPUP_ELECTROMAGNETIC_ELECTROSTATICFIELD, OnElectroStaticField)
	ON_THREAD_MESSAGE(ID_POPUP_OSCILLATORS_CYCLOTRON, OnCyclotron)
	ON_THREAD_MESSAGE(ID_POPUP_ELECTROMAGNETIC_CURRENTLOOP, OnCurrentLoop)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_VERHULSTDYNAMICS, OnVerhulstDynamics)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_6BODY, On6Body)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_CHAIN, OnChain)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_RANDOMCHAIN, OnRandomChain)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_COMPOUNDPENDULUM, OnCompoundPendulum)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_PHYSICAL_PENDULUM, OnPhysicalPendulum)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_TRAPPING, OnTrapping)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_TWOBODY, OnTwoNonShpericalBody)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_PENDULUMANDFIXEDCHARGE, OnPendulumAndFixedCharge)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_PENDULUMANDPLANARCHARGE, OnPendulumAndPlanarCharge)
	ON_THREAD_MESSAGE(ID_POPUP_CHAOTIC_SUBMERGED, OnSubmerged)
	ON_THREAD_MESSAGE(ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_PROBLEM214, Problem2_14)
	ON_THREAD_MESSAGE(ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_PROBLEM237, Problem2_37)
	ON_THREAD_MESSAGE(ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_EXAMPLE24, Example2_4)
	ON_THREAD_MESSAGE(ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_PROBLEM346, Problem3_46)
	ON_THREAD_MESSAGE(ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_PROBLEM351, Problem3_51)
	ON_THREAD_MESSAGE(ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_PROBLEM360, Problem3_60)
	ON_THREAD_MESSAGE(ID_POPUP_HOMEWORK_COLLEGEPHYSICSSERWAYFAUGHN_CHAPTER_7_EXAMPLE78, Example7_8)
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CGenExamp message handlers
