#if !defined(__HTML_Content_h_)
#define __HTML_Content_h_
// HTML_Content.h
//L"<TITLE>Quantum Mechanical Scattering in 2 Spatial Dimensions</TITLE>"
//L"<li>The (Home, End) keys translate along the z-axis [zoom (in, out) using translation]."
//L"<li>Drag with the right mouse button down and the 'Ctrl' key pressed to zoom [using projection]."


const _bstr_t bstrStartUp =
L"<HTML>"
L"<HEAD>"
L"<TITLE>Physics Simulator, Copyright 2000, Dr. P.L. Nash</TITLE>"
L"</HEAD>"
L"<BODY>"
L"<H3>Physics Simulator</h3>"
L"<P>"
L"<H4><HR></h4>"
L"<H5>The window with the coordinate axes is called the 'System Window'.</h5>"
L"<H5>The window to its right is called the 'Command Window'.</h5>"
L"<H5>The third simulator window near the bottom is called the 'Status Window'.</h5><BR><BR>"
L"<HR>"
L"<H3>Help (?)</h3><P>Click the right mouse button when over the <b>System Window</b> "
L"to diplay a menu of examples.<BR>Select an example.<BR>The commands that "
L"define the example are listed in the <b>Command Window</b>."
L"<b><HR></b>"
L"<b><HR></b>"
L"<H4>Classical Physics:</h4>"
L"The red horizontal axis is the x-axis. "
L"The green vertical axis is the y-axis. "
L"The blue axis normal to the screen is the z-axis.<BR><p>"
L"<H5>System Window:</h5>"
L"<ul TITLE=\"System Window\" TEXT=\"System Window\" NAME=\"System Window\">"
L"<li>Drag with the left mouse button down to rotate the view."
L"<li>The (Home, End) keys [zoom (in, out) using projection]."
L"<li>The (Page Up, Page Down) keys translate by ±1 along the z-axis [zoom (in, out) using translation]."
L"<li>The (Left, Right)   [respectively, (Up, Down)] arrow keys translate along the x-axis (resp., y-axis)."
L"<li>Both the screen and system (or world) coordinates of the point under the mouse are printed in the browser status line."
L"<li>The difference between the system coordinates of the point under the mouse and a selected point is also printed in the browser status line."
L"<li>This point is selected by left-clicking on a point while holding down the 'Shift' and 'Ctrl' keys."
L"<li><BR>"
L"<li>Left-click on an object to select it for measurment."
L"<li>Left-click on an object and drag it while holding down the 'Ctrl' key to quickly move it to a new position."
L"<li>Left-click on an object and drag it while holding down the 'Shift' and 'Ctrl' keys to rotate it to a new position."
L"<li>Left-click twice (pause between clicks) on an object's 'position' leaf's data (in the 'Simulation Tree') to enter a new position."
L"</ul>"
L"<BR><p>"
L"<H4>Quantum Physics:</h4>"
L"The red horizontal axis is the x-axis. The definitions of the other axes are dependent on the problem."
L"<HR>"
L"<HR>"
L"Most equations will not display correctly unless your web browser supports MathML"
L" <br><B>OR</b><BR>"
L" you have downloaded the 'EzMath' plugin "
L"<A href=\"http://www.w3.org/People/Raggett/ezmath1_1.zip\"><B>npezm32.dll</B></A> and copied it to the 'PLUGINS'"
L" subdirectory of your browser installation."
L" EzMath was developed by Dave Raggett and Davy Batsalle with the support of Hewlett Packard Laboratories"
L" [<A href=\"http://www.w3.org/People/Raggett/EzMath/EzMathPaper.html\">details</A>]."
L"<HR>"
L"To change the local support for MathML, first locate and click on the 'Envinonment' leaf of the tree control in the "
L"'Status Window'; then double-click the MathML node to toggle the selection to the desired value."
L"</BODY></html>";
///////////////////////////////////////////////////////////////////////////////
const _bstr_t bstrLogisticMap =
L"<HTML>"
L"<HEAD>"
L"<TITLE>Logistic Map, Copyright 2000, Dr. P.L. Nash</TITLE>"
L"</HEAD>"
L"<BODY>"
L"<H4>Logistic Map</h4>"
L"<HR>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 122 height=132"
L" alt=\"x sub {n+1} =  R x sub n ( 1 -  x sub n ),  where, 0 &lt;= R &lt;= 4  , 0 &lt;= x sub n &lt;= 1 \">"
L"<P>The Logistic Map birth rate 'R' is the vertical coordinate.<P>"
L"<P>The Logistic Map population x<sub>n</sub> is the horizontal coordinate.<P>"
L"<HR>"
L"<h4>Press the ESCAPE key to quit this example.</h4><hr>"
L"**Important**<p>"
L"The function of the arrow keys has changed from the default behavior.<P>"
L"<P>"
L"Definitions:"
L"<ul>"
L"<li>VK_HOME   =     'Home' key"
L"<li>VK_END    =     'End' key"
L"<li>VK_PRIOR   =     'Page Up' key"
L"<li>VK_NEXT    =     'Page Down' key"
L"<li>VK_TAB    =     'Tab' key"
L"<li>VK_LEFT   =     'Left' arrow key"
L"<li>VK_RIGHT  =     'Right' arrow key"
L"<li>VK_UP     =     'Up' arrow key"
L"<li>VK_DOWN   =     'Down' arrow key"
L"<li>bShift    =     'Shift' key is pressed"
L"<li>bCtrl     =     'Ctrl' key is pressed"
L"<li>g_Rate    =     Logistic Map birth rate 'R'"
L"<li>inc       =     \"g_Rate increases by\""
L"<li>dec       =     \"g_Rate decreases by\""
L"</ul>"
L"<P>"
L"Actions:"
L"<ul>"
L"<li>VK_HOME =>     g_Rate = 1"
L"<li>VK_END =>      g_Rate = 4"
L"<li>VK_LEFT bShift bCtrl =>     dec 0.0001"
L"<li>VK_LEFT bShift  =>     dec 0.001"
L"<li>VK_LEFT  bCtrl =>     dec 0.01"
L"<li>VK_LEFT  =>     dec 0.1"
L"<li>VK_RIGHT bShift bCtrl =>     inc 0.0001"
L"<li>VK_RIGHT bShift  =>     inc 0.001"
L"<li>VK_RIGHT  bCtrl =>     inc 0.01"
L"<li>VK_RIGHT  =>     inc 0.1"
L"<li>VK_UP bShift bCtrl =>     inc 0.00001"
L"<li>VK_UP bShift  =>     shift plot to right by 0.1"
L"<li>VK_UP  bCtrl =>     shift plot vertically up by 0.1"
L"<li>VK_UP  =>     zoom in by 0.1"
L"<li>VK_DOWN bShift bCtrl =>     dec 0.00001"
L"<li>VK_DOWN bShift  =>     shift plot to left by 0.1"
L"<li>VK_DOWN  bCtrl =>     shift plot vertically down by 0.1"
L"<li>VK_DOWN  =>     zoom out by 0.1"
L"<li>VK_PRIOR  =>     zoom in by 1"
L"<li>VK_NEXT  =>     zoom out by 1"
L"<li>VK_TAB  bCtrl =>     slow down 'play'"
L"<li>VK_TAB  =>     speed up 'play'"
L"</ul>"
L"<P><H5>Author: Dr. P.L. Nash</h5>"
L"</BODY></html>";

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

const _bstr_t bstrQM_2DScatt =
L"<HTML>"
L"<HEAD>"
L"<TITLE>Schrödinger Equation: Numerical Experiments in Two Dimensional Time Dependent Scattering from"
L"a Gaussian Potential Well/Barrier, Copyright 2000, Dr. P.L. Nash</TITLE>"
L"</HEAD>"
L"<BODY>"
L"<H4>Schrödinger Equation: Numerical Experiments in Two Dimensional Time Dependent Scattering from"
L"a Gaussian Potential Well/Barrier</h4>"
L"<H5>Author: Dr. P.L. Nash</h5>"
L"<HR>"
L"The red horizontal axis is the x-axis."
L"The green vertical axis is the y axis. "
L"The blue axis normal to the screen is the quantum mechanical relative probability density.<BR>"
L"Drag with the left mouse button down to rotate the view."
L"Drag with the right mouse button down to zoom.<br>"
L"To operate:"
L"<ul>"
L"<li>Produce a movie for a given set of parameters."
L"<li>Write all frames of this movie to the listed HDF5 data file."
L"<li>Read a HDF5 frame from this file for detailed inspection."
L"<li>The initial wavefunction and potential energy may be changed by modifying the displayed parameters."
L"<li>The wavefunction plot may be performed (with mixed results) using a convex hull calculated by "
L"<A href=\"http://www.geom.umn.edu/locate/qhull\">Qhull</A>"
L"or a surface spline calculated using the <A HREF=\"http://ocean.dt.navy.mil/dtnurbs/dtnurbs.htm\">"
L"DT NURBS Spline Geometry Library</A>."
L"</ul>"
L"<HR>"
L"Notes:"
L"<OL>"
L"<li>"
L"The Schrödinger equation is solved numerically on a 64 by 64 spatial lattice"
L"corresponding to the region (-1 < x < 1 , -1 < y < 1)."
L"<li>"
L"For a given time t, let<BR>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 202 height=28"
L" alt=\"P sub t (x,y) = Psi ^* ( x , y; t ) Psi ( x , y; t )"
L"\">"
L"<BR>be the probability density at the point (x,y)."
L"The displayed surface is described by ( x,y, P<sub>t</sub>(x,y) ),"
L"(-1 < x < 1 , -1 < y < 1)."
L"This program calculates ( 64 * 64 ) points on this surface that"
L"correspond to the x-y coordinates of the"
L"64 * 64 nodes at the intersections of the spatial lattice."
L"An interpolating spline surface goes through each of these ( 64 * 64 ) points. "
L"An approximating spline surface comes as close to each of the"
L"( 64 * 64 ) points as possible while satisfying other restrictions."
L"<li>"
L"The surface spline is computed using a set of "
L"( 64 * 64 ) * (Increase Spline Resolution by N)"
L"randomly generated points in the interval"
L"(-1 < x < 1 , -1 < y < 1). Here,"
L"0 < N < 32 is an integer. "
L"<li>"
L"Each time the 'Surface Spline' button"
L"is pushed a new set of ( 64 * 64 ) * N points"
L"is randomly generated. The independent (x,y) coordinates"
L"of these points are fed to a DT NURBS Spline Geometry Library function "
L"that returns a value P<sub>t</sub>(x,y) for each point."
L"A (usually, slightly) different surface plot is produced each time."
L"</ol>"
L"<HR>"
L"<H5>Details Summary</H5><P>Initial wave function:<BR>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 357 height=63"
L" alt=\"Psi ( x , y; t = 0 ) = {1 / sqrt{ 2 pi a} } e^{i ( k sub x x + k sub y y )} e^{- (1 / 4 a^2}[(x - x sub 0)^2 +(y - y sub 0)^2] }"
L"\">"
L"<H4>Unitary Evolution Methods ()</H4><P>"
L"<HR>"
L"<H4>Unitary Evolution Methods: 1-D versions; 2-D are iterations of 1-D</H4><P>"
L"<A NAME=\"Nash-Chen\">"
L"<H5>Nash-Chen</H5></A>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 461 height=52"
L" alt=\"Psi sub x (t  +  delta t)  = e^{ -i  lambda (1  +  U sub x ) }  J sub 0 (lambda) Psi sub x (t)"
L"  +  sum from x'=1 to infinity of  i^{x'} J sub {x'} (lambda) [ Psi sub {x - x'} (t) + Psi sub {x + x'} (t) ]\">"
L"<BR>for x = 0, 1, 2, ..., N - 1, where<br> "
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 167 height=24"
L" alt=\"Psi sub {x+N} (t  +  delta t)  = Psi sub x (t  +  delta t) \">. "
L"The J<sub>n</sub> are Bessel functions of the first kind.<BR>"
L"P. L. Nash and L.Y. Chen, Efficient finite difference solutions to the time-dependent Schrodinger"
L"equation, <em>Journal of Computational Physics</em>, <strong>130</strong>, p266 (1997)."
L"<HR>"
\
L"<A NAME=\"Cayley\"><H5>Cayley</H5></A>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 294 height=92"
L" alt=\"{e^{{i/2} H delta t}}Psi  (t  +  delta t)  = {e^{-{i/2} H delta t}}Psi  (t  -  delta t) , (1 + {i/2} H delta t }Psi  (t  +  delta t)  = (1-{i/2} H delta t}Psi  (t  -  delta t) \">"
L"<BR>This yields a tridiagonal system wthe previous approximation for the Laplacian"
\
L"<HR>"
L"<H6>Periodic Cayley</H6>"
L"is the tridiagonal Cayley system plus two additional matrix elements in "
L"the coefficient matrix at locations (first row, last column) and"
L"(last row, first column). This generates a sparse system. "
L"The solution is periodic.<BR>"
L"<HR>"
L"</BODY></html>";

///////////////////////////////////////////////////////////////////////////////


const _bstr_t bstrQM_1DScatt =
L"<HTML>"
L"<HEAD>"
L"<TITLE>Schrödinger Equation: Numerical Experiments in One Dimensional Time Dependent Scattering</TITLE>"
L"</HEAD>"
L"<BODY>"
L"<H5>Schrödinger Equation: Numerical Experiments in One Dimensional Time Dependent Scattering</h5>"
\
L"The red curve is the initial probability density, blue (yellow) curve the real (imaginary) part of the wave function. "
L"<BR>"
L"The dark green curve is the potential energy V. "
L"Regions where V = 0 are said to be the external vacuum. <BR>"
L"In order to modify the potential:<BR>"
L"<UL>"
L"<LI>Left-click on the external vacuum to create a new potential well/barrier."
L"<LI>Left-click and drag an existing potential well/barrier to change its depth or height."
L"<LI>Control-Left-click and drag an existing potential well/barrier to change its width."
L"<LI>To delete an existing potential well/barrier, left-click and drag it toward the trashcan until the mouse is over the trashcan; then release the mouse."
L"</UL>"
\
\
\
L"<br>"
L"<HR>"
L"<H5>Details Summary</H5><P>Initial wave function:<BR>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 228 height=92"
L" alt=\"Psi ( x , 0 ) =  {1 / (2 pi)^{1/4}}  {1 / sqrt a } e^{i k x } e^{- (x - x sub 0)^2 / 4 a^2 }\">"
L"<BR>0 <= x <= 1<BR>"
L"N = #nodes  in spatial lattice<BR>"
L"a = delta x = spatial step size = 1 / (N-1) <BR>"
L"x --> a x ,  where x = 0, 1, 2, ..., N-1<BR>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 246 height=48"
L" alt=\"div grad F | sub x = {1 / a^2 } (F sub {x+1} - 2 F sub x + F sub {x-1}) + etc"
L"\">"
\
L"<BR>Maximum wavenumber:<BR>"
L"k<sub>max</sub> a = 2 pi => -pi/a < k < pi/a => -pi/2a < k<sub>unique velocity</sub> < pi/2a <p>"
\
\
L"Stability:<BR>"
L"T = delta t = time step size<BR>"
L"Evolution methods are stable if<BR>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 106 height=50"
L" alt=\"lambda = {h / 2 pi} {delta t / m delta x^2}"
L"\">"
L"<BR>is between 0 and 1;  in these simulations we take m = 1 and <BR>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 56 height=43"
L" alt=\"{h / 2 pi} =1"
L"\">"
\
\
L"<p>Non-dimensionalized potential energy:<BR>"
L"V = potential energy<BR>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 123 height=43"
L" alt=\"U = { ( 2 pi / h )^2 } m a^2 V"
L"\">"
L"<BR>where U = non-dimensionalized potential energy =  "
L"±(rectangle.bottom - rectangle.top) · ( VALUE of 'Scale potential energy by' entry) <BR>"
\
L"<HR>"
L"<H4>Unitary Evolution Methods</H4><P>"
L"<A NAME=\"Nash-Chen\">"
L"<H5>Nash-Chen</H5></A>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 461 height=52"
L" alt=\"Psi sub x (t  +  delta t)  = e^{ -i  lambda (1  +  U sub x ) }  J sub 0 (lambda) Psi sub x (t)"
L"  +  sum from x'=1 to infinity of  i^{x'} J sub {x'} (lambda) [ Psi sub {x - x'} (t) + Psi sub {x + x'} (t) ]\">"
L"<BR>for x = 0, 1, 2, ..., N - 1, where<br> "
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 167 height=24"
L" alt=\"Psi sub {x+N} (t  +  delta t)  = Psi sub x (t  +  delta t) \">. "
L"The J<sub>n</sub> are Bessel functions of the first kind.<BR>"
L"P. L. Nash and L.Y. Chen, Efficient finite difference solutions to the time-dependent Schrodinger"
L"equation, <em>Journal of Computational Physics</em>, <strong>130</strong>, p266 (1997)."
L"<HR>"
\
L"<A NAME=\"Cayley\"><H5>Cayley</H5></A>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 294 height=92"
L" alt=\"{e^{{i/2} H delta t}}Psi  (t  +  delta t)  = {e^{-{i/2} H delta t}}Psi  (t  -  delta t) , (1 + {i/2} H delta t }Psi  (t  +  delta t)  = (1-{i/2} H delta t}Psi  (t  -  delta t) \">"
L"<BR>This yields a tridiagonal system wthe previous approximation for the Laplacian"
\
L"<HR>"
\
L"<A NAME=\"PeriodicCayley\"><H5>Periodic Cayley</H5></A>"
L"The tridiagonal Cayley system plus two additional matrix elements in "
L"the coefficient matrix at locations (first row, last column) and"
L"(last row, first column). This generates a sparse system that"
L"cannot be solved as efficiently as the tridiagonal system. "
L"The solution is periodic."
L"When possible, it is more efficient to place potential barriers on the "
L"left and right boundaries and use the Cayley tridiagonal system.<BR>"
\
\
\
L"</BODY>"
L"</HTML>";

///////////////////////////////////////////////////////////////////////////////

const _bstr_t bstrSuperposition =
L"<HTML>"
L"<HEAD>"
L"<TITLE>Investigation of Particle Waves</TITLE>"
L"</HEAD>"
L"<BODY>"
L"Relative Probability Density of a Free Particle in Spacetime"
L"<HR>"
L"The red horizontal axis is the x-axis.<br>"
L"The blue axis normal to the screen is the time axis.<br>"
L"The green vertical axis is the quantum mechanical relative probability density.<P>"
L"Drag with the left mouse button down to rotate the view.<BR>"
L"Drag with the right mouse button down to zoom.<BR>"
L"<HR>"
L"Wavefunction:<BR>"
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 163 height=62"
L" alt=\"Psi ( x , t ) =  sum from k of (A sub k e^{i k x  - i k^2 t/2 )\">"
L"<BR>where  "
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 61 height=44"
L" alt=\"A sub k = either 1 or 0\">"
L"<BR>and  "
L"<embed type=\"text/ezmath\""
L" pluginspage=\"npezm32.dll\""
L" align=absmiddle"
L" width= 56 height=43"
L" alt=\"h / 2  pi = 1 = particle mass\">"
L"</BODY></html>";

///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////

const _bstr_t bstrElectroStatics =
L"<HTML>"
L"<HEAD>"
L"<TITLE>The Electric Field Due to a  Static Charge Distribution</TITLE>"
L"</HEAD>"
L"<BODY>"
L"The Electric Field Due to a  Static Charge Distribution"
L"<HR>"
L"<p>Instruction Summary: "
L"<ul>"
L"  <li>shift-left-click in the 'System Window' to create a charged particle of charge +1</li>"
L"  <li>the electric field through the point under the mouse cursor is drawn</li>"
L"  <li>an interval of the intersection of an equipotential surface through the point "
L"    under the mouse cursor with the x-y plane is shown</li>"
L"  <li>left-click on a charged particle to <b>select</b> it</li>"
L"  <li>drag a <b>selected</b> charged particle to move it</li>"
L"  <li>for a <b>selected</b> charged particle, press INSERT to edit its charge</li>"
L"  <li>for a <b>selected</b> charged particle, press DELETE to remove it</li>"
L"  <li>control-left-click on a point to begin the generation the electric field lines"
L"    through the point under the mouse cursor</li>"
L"  <li>press the 'Abort Fieldline' button to stop fieldline production</li>"
L"</ul>"
L"</BODY></html>";


///////////////////////////////////////////////////////////////////////////////

const _bstr_t bstrCurrentLoop =
L"<HTML>"
L"<HEAD>"
L"<TITLE>The Magnetic Field Due to a  Steady Current in a Closed Loop</TITLE>"
L"</HEAD>"
L"<BODY>"
L"<h4>The Magnetic Field Due to a  Steady Current in a Closed Loop (Biot-Savart Law)</h4>"
L"This example performs approximate numerical calculations of the magnetic field vector at a point "
L"due to to a steady current in a closed loop, "
L"and of the magnetic field line through the point.</p>"
L"<p>You may deform a copy of this closed curve by dragging certain points on its boundary. "
L"<HR>"
L"<p>The blue closed curve is an ideal conductor carrying a steady counter-clockwise "
L"current. The initial orientation of this loop is called the <strong>default view</strong>. "
L"The x-axis is horizontal and x increases from left to right. The y-axis is vertical "
L"and y increases from bottom to top. The z-axis is normal to your monitor screen; the "
L"direction of the positive z-axis is given by the right-hand-rule and points from the "
L"screen toward you. </p>"
L"Approximate numerical calculations of the magnetic field vector at a point and of the magnetic field "
L"line through a point may be performed as follows. </p>"
L"<p><h5>Instruction Summary: </h5>"
L"<ul>"
L"  <li>Press the 'Shift' key while moving the mouse in the 'System Window' "
L"to display the magnetic field at the point under the mouse cursor.</li>"
L"  <li>[default view only] Control-left-click on a point to begin the generation the magnetic field lines "
L"    through the point under the mouse cursor. A portion of an "
L" approximate fieldline through the point is calculated and displayed. When this calculation is completed "
L" a new one begins for the point currently under the mouse cursor.</li>"
L"  <li>Press the 'Abort Fieldline' button to stop fieldline production.</li>"
L"  <li>To modify the current loop geometry, enter 'sys.edit.currentLoopMagneticField' in the Command Window (without the quotes). "
L"This will bring up a popup window like the one you just closed. </li>"
L"  <li>Position the mouse cursor above the curve in the popup window to locate its <strong>dragable</strong> nodes (hotspots).</li>"
L"  <li>Drag the hotspots on the loop to new positions to reshape the closed current loop. Click 'OK' when done.</li>"
L"</ul>"
L"<h6>note:</h6>"
L"<strong>Completely spurious results</strong> "
L" are obtained if you control-left-click too close to the blue loop. "
L"While spurious results may be interesting visually, they should be reminders of the "
L"limits of this crude approximation."
L"</BODY></html>";

///////////////////////////////////////////////////////////////////////////////
// HTML_ContentMathML.h

const _bstr_t bstrQM_2DScatt2 =
L"<HTML>"
L"<HEAD>"
L"<TITLE>Schrödinger Equation: Numerical Experiments in Two Dimensional Time Dependent Scattering from"
L"a Gaussian Potential Well/Barrier, Copyright 2000, Dr. P.L. Nash</TITLE>"
L"</HEAD>"
L"<BODY>"
L"<H4>Schrödinger Equation: Numerical Experiments in Two Dimensional Time Dependent Scattering from"
L"a Gaussian Potential Well/Barrier</h4>"
L"<H5>Author: Dr. P.L. Nash</h5>"
L"<HR>"
L"The red horizontal axis is the x-axis."
L"The green vertical axis is the y axis. "
L"The blue axis normal to the screen is the quantum mechanical relative probability density.<BR>"
L"Drag with the left mouse button down to rotate the view."
L"Drag with the right mouse button down to zoom.<br>"
L"To operate:"
L"<ul>"
L"<li>Produce a movie for a given set of parameters."
L"<li>Write all frames of this movie to the listed HDF5 data file."
L"<li>Read a HDF5 frame from this file for detailed inspection."
L"<li>The initial wavefunction and potential energy may be changed by modifying the displayed parameters."
L"<li>The wavefunction plot may be performed (with mixed results) using a convex hull calculated by "
L"<A href=\"http://www.geom.umn.edu/locate/qhull\">Qhull</A>"
L"or a surface spline calculated using the <A HREF=\"http://ocean.dt.navy.mil/dtnurbs/dtnurbs.htm\">"
L"DT NURBS Spline Geometry Library</A>."
L"</ul>"
L"<HR>"
L"Notes:"
L"<OL>"
L"<li>"
L"The Schrödinger equation is solved numerically on a 64 by 64 spatial lattice"
L"corresponding to the region (-1 < x < 1 , -1 < y < 1)."
L"<li>"
L"For a given time t, let<BR>"
L"<XML ID=\"XMLID1\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <times/>"
L"      <msub>"
L"         <ci>P</ci>"
L"         <ci>t</ci>"
L"      </msub>"
L"      <mfence>"
L"         <ci>x</ci>"
L"         <ci>y</ci>"
L"      </mfence>"
L"   </apply>"
L"   <apply>"
L"      <times/>"
L"      <apply>"
L"         <power/>"
L"         <mo>&Psi;</mo>"
L"         <mo><times/></mo>"
L"      </apply>"
L"      <mfence>"
L"         <ci>x</ci>"
L"         <ci>y</ci>"
L"         <ci>t</ci>"
L"      </mfence>"
L"      <mo>&Psi;</mo>"
L"      <mfence>"
L"         <ci>x</ci>"
L"         <ci>y</ci>"
L"         <ci>t</ci>"
L"      </mfence>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"\">"
L"<BR>be the probability density at the point (x,y)."
L"The displayed surface is described by ( x,y, P<sub>t</sub>(x,y) ),"
L"(-1 < x < 1 , -1 < y < 1)."
L"This program calculates ( 64 * 64 ) points on this surface that"
L"correspond to the x-y coordinates of the"
L"64 * 64 nodes at the intersections of the spatial lattice."
L"An interpolating spline surface goes through each of these ( 64 * 64 ) points. "
L"An approximating spline surface comes as close to each of the"
L"( 64 * 64 ) points as possible while satisfying other restrictions."
L"<li>"
L"The surface spline is computed using a set of "
L"( 64 * 64 ) * (Increase Spline Resolution by N)"
L"randomly generated points in the interval"
L"(-1 < x < 1 , -1 < y < 1). Here,"
L"0 < N < 32 is an integer. "
L"<li>"
L"Each time the 'Surface Spline' button"
L"is pushed a new set of ( 64 * 64 ) * N points"
L"is randomly generated. The independent (x,y) coordinates"
L"of these points are fed to a DT NURBS Spline Geometry Library function "
L"that returns a value P<sub>t</sub>(x,y) for each point."
L"A (usually, slightly) different surface plot is produced each time."
L"</ol>"
L"<HR>"
L"<H5>Details Summary</H5><P>Initial wave function:<BR>"
L"<XML ID=\"XMLID2\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <times/>"
L"      <mo>&Psi;</mo>"
L"      <mfence>"
L"         <ci>x</ci>"
L"         <ci>y</ci>"
L"         <reln>"
L"            <eq/>"
L"            <ci>t</ci>"
L"            <cn>0</cn>"
L"         </reln>"
L"      </mfence>"
L"   </apply>"
L"   <apply>"
L"      <times/>"
L"      <apply>"
L"         <over/>"
L"         <cn>1</cn>"
L"         <apply><root/>"
L"            <apply>"
L"               <times/>"
L"               <cn>2</cn>"
L"               <mo>&pi;</mo>"
L"               <ci>a</ci>"
L"            </apply>"
L"         </apply>"
L"      </apply>"
L"      <apply>"
L"         <power/>"
L"         <ci>e</ci>"
L"         <apply>"
L"            <times/>"
L"            <ci>i</ci>"
L"            <mfence>"
L"               <apply>"
L"                  <plus/>"
L"                  <apply>"
L"                     <times/>"
L"                     <msub>"
L"                        <ci>k</ci>"
L"                        <ci>x</ci>"
L"                     </msub>"
L"                     <ci>x</ci>"
L"                  </apply>"
L"                  <apply>"
L"                     <times/>"
L"                     <msub>"
L"                        <ci>k</ci>"
L"                        <ci>y</ci>"
L"                     </msub>"
L"                     <ci>y</ci>"
L"                  </apply>"
L"               </apply>"
L"            </mfence>"
L"         </apply>"
L"      </apply>"
L"      <apply>"
L"         <power/>"
L"         <ci>e</ci>"
L"         <apply>"
L"            <times/>"
L"            <apply>"
L"               <minus/>"
L"               <mfence>"
L"                  <apply>"
L"                     <over/>"
L"                     <cn>1</cn>"
L"                     <apply>"
L"                        <times/>"
L"                        <cn>4</cn>"
L"                        <apply>"
L"                           <power/>"
L"                           <ci>a</ci>"
L"                           <cn>2</cn>"
L"                        </apply>"
L"                     </apply>"
L"                  </apply>"
L"               </mfence>"
L"            </apply>"
L"            <mfence>"
L"               <apply>"
L"                  <plus/>"
L"                  <apply>"
L"                     <power/>"
L"                     <mfence>"
L"                        <apply>"
L"                           <minus/>"
L"                           <ci>x</ci>"
L"                           <msub>"
L"                              <ci>x</ci>"
L"                              <cn>0</cn>"
L"                           </msub>"
L"                        </apply>"
L"                     </mfence>"
L"                     <cn>2</cn>"
L"                  </apply>"
L"                  <apply>"
L"                     <power/>"
L"                     <mfence>"
L"                        <apply>"
L"                           <minus/>"
L"                           <ci>y</ci>"
L"                           <msub>"
L"                              <ci>y</ci>"
L"                              <cn>0</cn>"
L"                           </msub>"
L"                        </apply>"
L"                     </mfence>"
L"                     <cn>2</cn>"
L"                  </apply>"
L"               </apply>"
L"            </mfence>"
L"         </apply>"
L"      </apply>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"\">"
L"<HR>"
L"<H4>Unitary Evolution Methods: 1-D versions; 2-D are iterations of 1-D</H4><P>"
L"<A NAME=\"Nash-Chen\">"
L"<H5>Nash-Chen</H5></A>"
L"<XML ID=\"XMLID6\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <times/>"
L"      <msub>"
L"         <mo>&Psi;</mo>"
L"         <ci>x</ci>"
L"      </msub>"
L"      <mfence>"
L"         <apply>"
L"            <plus/>"
L"            <ci>t</ci>"
L"            <apply>"
L"               <times/>"
L"               <mo>&delta;</mo>"
L"               <ci>t</ci>"
L"            </apply>"
L"         </apply>"
L"      </mfence>"
L"   </apply>"
L"   <apply>"
L"      <plus/>"
L"      <apply>"
L"         <times/>"
L"         <apply>"
L"            <power/>"
L"            <ci>e</ci>"
L"            <apply>"
L"               <times/>"
L"               <apply>"
L"                  <minus/>"
L"                  <ci>i</ci>"
L"               </apply>"
L"               <mo>&lambda;</mo>"
L"               <mfence>"
L"                  <apply>"
L"                     <plus/>"
L"                     <cn>1</cn>"
L"                     <msub>"
L"                        <ci>U</ci>"
L"                        <ci>x</ci>"
L"                     </msub>"
L"                  </apply>"
L"               </mfence>"
L"            </apply>"
L"         </apply>"
L"         <msub>"
L"            <ci>J</ci>"
L"            <cn>0</cn>"
L"         </msub>"
L"         <mfence>"
L"            <mo>&lambda;</mo>"
L"         </mfence>"
L"         <msub>"
L"            <mo>&Psi;</mo>"
L"            <ci>x</ci>"
L"         </msub>"
L"         <mfence>"
L"            <ci>t</ci>"
L"         </mfence>"
L"      </apply>"
L"      <apply>"
L"         <sum/>"
L"         <lowlimit>"
L"            <cn>1</cn>"
L"         </lowlimit>"
L"         <uplimit>"
L"            <mo>&infin;</mo>"
L"         </uplimit>"
L"         <bvar>"
L"            <apply>"
L"               <times/>"
L"               <ci>x</ci>"
L"               <ci>'</ci>"
L"            </apply>"
L"         </bvar>"
L"         <apply>"
L"            <times/>"
L"            <apply>"
L"               <power/>"
L"               <ci>i</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <ci>x</ci>"
L"                  <ci>'</ci>"
L"               </apply>"
L"            </apply>"
L"            <msub>"
L"               <ci>J</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <ci>x</ci>"
L"                  <ci>'</ci>"
L"               </apply>"
L"            </msub>"
L"            <mfence>"
L"               <mo>&lambda;</mo>"
L"            </mfence>"
L"            <mfence>"
L"               <apply>"
L"                  <plus/>"
L"                  <apply>"
L"                     <times/>"
L"                     <msub>"
L"                        <mo>&Psi;</mo>"
L"                        <apply>"
L"                           <minus/>"
L"                           <ci>x</ci>"
L"                           <apply>"
L"                              <times/>"
L"                              <ci>x</ci>"
L"                              <ci>'</ci>"
L"                           </apply>"
L"                        </apply>"
L"                     </msub>"
L"                     <mfence>"
L"                        <ci>t</ci>"
L"                     </mfence>"
L"                  </apply>"
L"                  <apply>"
L"                     <times/>"
L"                     <msub>"
L"                        <mo>&Psi;</mo>"
L"                        <apply>"
L"                           <plus/>"
L"                           <ci>x</ci>"
L"                           <apply>"
L"                              <times/>"
L"                              <ci>x</ci>"
L"                              <ci>'</ci>"
L"                           </apply>"
L"                        </apply>"
L"                     </msub>"
L"                     <mfence>"
L"                        <ci>t</ci>"
L"                     </mfence>"
L"                  </apply>"
L"               </apply>"
L"            </mfence>"
L"         </apply>"
L"      </apply>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"<BR>for x = 0, 1, 2, ..., N - 1, where<br> "
L"<XML ID=\"XMLID7\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <times/>"
L"      <msub>"
L"         <mo>&Psi;</mo>"
L"         <apply>"
L"            <plus/>"
L"            <ci>x</ci>"
L"            <ci>N</ci>"
L"         </apply>"
L"      </msub>"
L"      <mfence>"
L"         <apply>"
L"            <plus/>"
L"            <ci>t</ci>"
L"            <apply>"
L"               <times/>"
L"               <mo>&delta;</mo>"
L"               <ci>t</ci>"
L"            </apply>"
L"         </apply>"
L"      </mfence>"
L"   </apply>"
L"   <apply>"
L"      <times/>"
L"      <msub>"
L"         <mo>&Psi;</mo>"
L"         <ci>x</ci>"
L"      </msub>"
L"      <mfence>"
L"         <apply>"
L"            <plus/>"
L"            <ci>t</ci>"
L"            <apply>"
L"               <times/>"
L"               <mo>&delta;</mo>"
L"               <ci>t</ci>"
L"            </apply>"
L"         </apply>"
L"      </mfence>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"The J<sub>n</sub> are Bessel functions of the first kind.<BR>"
L"P. L. Nash and L.Y. Chen, Efficient finite difference solutions to the time-dependent Schrodinger"
L"equation, <em>Journal of Computational Physics</em>, <strong>130</strong>, p266 (1997)."
L"<HR>"
\
L"<A NAME=\"Cayley\"><H5>Cayley</H5></A>"
L"<XML ID=\"XMLID8\">"
L"<ea>"
L"   <reln>"
L"      <eq/>"
L"      <apply>"
L"         <times/>"
L"         <apply>"
L"            <power/>"
L"            <ci>e</ci>"
L"            <apply>"
L"               <times/>"
L"               <apply>"
L"                  <over/>"
L"                  <ci>i</ci>"
L"                  <cn>2</cn>"
L"               </apply>"
L"               <ci>H</ci>"
L"               <mo>&delta;</mo>"
L"               <ci>t</ci>"
L"            </apply>"
L"         </apply>"
L"         <mo>&Psi;</mo>"
L"         <mfence>"
L"            <apply>"
L"               <plus/>"
L"               <ci>t</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"      </apply>"
L"      <apply>"
L"         <times/>"
L"         <apply>"
L"            <power/>"
L"            <ci>e</ci>"
L"            <apply>"
L"               <times/>"
L"               <apply>"
L"                  <minus/>"
L"                  <apply>"
L"                     <over/>"
L"                     <ci>i</ci>"
L"                     <cn>2</cn>"
L"                  </apply>"
L"               </apply>"
L"               <ci>H</ci>"
L"               <mo>&delta;</mo>"
L"               <ci>t</ci>"
L"            </apply>"
L"         </apply>"
L"         <mo>&Psi;</mo>"
L"         <mfence>"
L"            <apply>"
L"               <minus/>"
L"               <ci>t</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"      </apply>"
L"   </reln>"
L"   <reln>"
L"      <eq/>"
L"      <apply>"
L"         <times/>"
L"         <mfence>"
L"            <apply>"
L"               <plus/>"
L"               <cn>1</cn>"
L"               <apply>"
L"                  <times/>"
L"                  <apply>"
L"                     <over/>"
L"                     <ci>i</ci>"
L"                     <cn>2</cn>"
L"                  </apply>"
L"                  <ci>H</ci>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"         <mo>&Psi;</mo>"
L"         <mfence>"
L"            <apply>"
L"               <plus/>"
L"               <ci>t</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"      </apply>"
L"      <apply>"
L"         <times/>"
L"         <mfence>"
L"            <apply>"
L"               <minus/>"
L"               <cn>1</cn>"
L"               <apply>"
L"                  <times/>"
L"                  <apply>"
L"                     <over/>"
L"                     <ci>i</ci>"
L"                     <cn>2</cn>"
L"                  </apply>"
L"                  <ci>H</ci>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"         <mo>&Psi;</mo>"
L"         <mfence>"
L"            <apply>"
L"               <minus/>"
L"               <ci>t</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"      </apply>"
L"   </reln>"
L"</ea>"
L"</XML>"
L"<BR>This yields a tridiagonal system wthe previous approximation for the Laplacian"
\
L"<HR>"
L"<H6>Periodic Cayley</H6>"
L"is the tridiagonal Cayley system plus two additional matrix elements in "
L"the coefficient matrix at locations (first row, last column) and"
L"(last row, first column). This generates a sparse system. "
L"The solution is periodic.<BR>"
L"<HR>"
L"</BODY></html>";

///////////////////////////////////////////////////////////////////////////////


const _bstr_t bstrQM_1DScatt2 =
L"<HTML>"
L"<HEAD>"
L"<TITLE>Schrödinger Equation: Numerical Experiments in One Dimensional Time Dependent Scattering</TITLE>"
L"</HEAD>"
L"<BODY>"
L"<H5>Schrödinger Equation: Numerical Experiments in One Dimensional Time Dependent Scattering</h5>"
\
L"The red curve is the initial probability density, blue (yellow) curve the real (imaginary) part of the wave function. "
L"<BR>"
L"The dark green curve is the potential energy V. "
L"Regions where V = 0 are said to be the external vacuum. <BR>"
L"In order to modify the potential:<BR>"
L"<UL>"
L"<LI>Left-click on the external vacuum to create a new potential well/barrier."
L"<LI>Left-click and drag an existing potential well/barrier to change its depth or height."
L"<LI>Control-Left-click and drag an existing potential well/barrier to change its width."
L"<LI>To delete an existing potential well/barrier, left-click and drag it toward the trashcan until the mouse is over the trashcan; then release the mouse."
L"</UL>"
\
\
\
L"<br>"
L"<HR>"
L"<H5>Details Summary</H5><P>Initial wave function:<BR>"
L"<XML ID=\"XMLID1\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <times/>"
L"      <mo>&Psi;</mo>"
L"      <mfence>"
L"         <ci>x</ci>"
L"         <cn>0</cn>"
L"      </mfence>"
L"   </apply>"
L"   <apply>"
L"      <times/>"
L"      <apply>"
L"         <over/>"
L"         <cn>1</cn>"
L"         <apply>"
L"            <power/>"
L"            <mfence>"
L"               <apply>"
L"                  <times/>"
L"                  <cn>2</cn>"
L"                  <mo>&pi;</mo>"
L"               </apply>"
L"            </mfence>"
L"            <apply>"
L"               <over/>"
L"               <cn>1</cn>"
L"               <cn>4</cn>"
L"            </apply>"
L"         </apply>"
L"      </apply>"
L"      <apply>"
L"         <over/>"
L"         <cn>1</cn>"
L"         <apply><root/>"
L"            <ci>a</ci>"
L"         </apply>"
L"      </apply>"
L"      <apply>"
L"         <power/>"
L"         <ci>e</ci>"
L"         <apply>"
L"            <times/>"
L"            <ci>i</ci>"
L"            <ci>k</ci>"
L"            <ci>x</ci>"
L"         </apply>"
L"      </apply>"
L"      <apply>"
L"         <power/>"
L"         <ci>e</ci>"
L"         <apply>"
L"            <over/>"
L"            <apply>"
L"               <minus/>"
L"               <apply>"
L"                  <power/>"
L"                  <mfence>"
L"                     <apply>"
L"                        <minus/>"
L"                        <ci>x</ci>"
L"                        <msub>"
L"                           <ci>x</ci>"
L"                           <cn>0</cn>"
L"                        </msub>"
L"                     </apply>"
L"                  </mfence>"
L"                  <cn>2</cn>"
L"               </apply>"
L"            </apply>"
L"            <apply>"
L"               <times/>"
L"               <cn>4</cn>"
L"               <apply>"
L"                  <power/>"
L"                  <ci>a</ci>"
L"                  <cn>2</cn>"
L"               </apply>"
L"            </apply>"
L"         </apply>"
L"      </apply>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"<BR>0 <= x <= 1<BR>"
L"N = #nodes  in spatial lattice<BR>"
L"a = delta x = spatial step size = 1 / (N-1) <BR>"
L"x --> a x ,  where x = 0, 1, 2, ..., N-1<BR>"
L"<XML ID=\"XMLID2\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <times/>"
L"      <apply>"
L"         <div/>"
L"         <apply>"
L"            <grad/>"
L"            <ci>F</ci>"
L"         </apply>"
L"      </apply>"
L"      <msub>"
L"         <mo>|</mo>"
L"         <ci>x</ci>"
L"      </msub>"
L"   </apply>"
L"   <apply>"
L"      <plus/>"
L"      <apply>"
L"         <times/>"
L"         <apply>"
L"            <over/>"
L"            <cn>1</cn>"
L"            <apply>"
L"               <power/>"
L"               <ci>a</ci>"
L"               <cn>2</cn>"
L"            </apply>"
L"         </apply>"
L"         <mfence>"
L"            <apply>"
L"               <plus/>"
L"               <apply>"
L"                  <minus/>"
L"                  <msub>"
L"                     <ci>F</ci>"
L"                     <apply>"
L"                        <plus/>"
L"                        <ci>x</ci>"
L"                        <cn>1</cn>"
L"                     </apply>"
L"                  </msub>"
L"                  <apply>"
L"                     <times/>"
L"                     <cn>2</cn>"
L"                     <msub>"
L"                        <ci>F</ci>"
L"                        <ci>x</ci>"
L"                     </msub>"
L"                  </apply>"
L"               </apply>"
L"               <msub>"
L"                  <ci>F</ci>"
L"                  <apply>"
L"                     <minus/>"
L"                     <ci>x</ci>"
L"                     <cn>1</cn>"
L"                  </apply>"
L"               </msub>"
L"            </apply>"
L"         </mfence>"
L"      </apply>"
L"      <mo>&hellip;</mo>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"\">"
\
L"<BR>Maximum wavenumber:<BR>"
L"k<sub>max</sub> a = 2 pi => -pi/a < k < pi/a => -pi/2a < k<sub>unique velocity</sub> < pi/2a <p>"
\
\
L"Stability:<BR>"
L"T = delta t = time step size<BR>"
L"Evolution methods are stable if<BR>"
L"<XML ID=\"XMLID3\">"
L"<reln>"
L"   <eq/>"
L"   <mo>&lambda;</mo>"
L"   <apply>"
L"      <times/>"
L"      <apply>"
L"         <over/>"
L"         <ci>h</ci>"
L"         <apply>"
L"            <times/>"
L"            <cn>2</cn>"
L"            <mo>&pi;</mo>"
L"         </apply>"
L"      </apply>"
L"      <apply>"
L"         <over/>"
L"         <apply>"
L"            <times/>"
L"            <mo>&delta;</mo>"
L"            <ci>t</ci>"
L"         </apply>"
L"         <apply>"
L"            <times/>"
L"            <ci>m</ci>"
L"            <mo>&delta;</mo>"
L"            <apply>"
L"               <power/>"
L"               <ci>x</ci>"
L"               <cn>2</cn>"
L"            </apply>"
L"         </apply>"
L"      </apply>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"\">"
L"<BR>is between 0 and 1;  in these simulations we take mass <sub>particle</sub> = 1 and <BR>"
L"<XML ID=\"XMLID4\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <over/>"
L"      <ci>h</ci>"
L"      <apply>"
L"         <times/>"
L"         <cn>2</cn>"
L"         <mo>&pi;</mo>"
L"      </apply>"
L"   </apply>"
L"   <cn>1</cn>"
L"</reln>"
L"</XML>"
L"\">"
\
\
L"<p>Non-dimensionalized potential energy:<BR>"
L"V = potential energy<BR>"
L"<XML ID=\"XMLID5\">"
L"<reln>"
L"   <eq/>"
L"   <ci>U</ci>"
L"   <apply>"
L"      <times/>"
L"      <apply>"
L"         <power/>"
L"         <mfence>"
L"            <apply>"
L"               <over/>"
L"               <apply>"
L"                  <times/>"
L"                  <cn>2</cn>"
L"                  <mo>&pi;</mo>"
L"               </apply>"
L"               <ci>h</ci>"
L"            </apply>"
L"         </mfence>"
L"         <cn>2</cn>"
L"      </apply>"
L"      <ci>m</ci>"
L"      <apply>"
L"         <power/>"
L"         <ci>a</ci>"
L"         <cn>2</cn>"
L"      </apply>"
L"      <ci>V</ci>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"\">"
L"<BR>where U = non-dimensionalized potential energy =  "
L"±(rectangle.bottom - rectangle.top) · ( VALUE of 'Scale potential energy by' entry) <BR>"
\
L"<HR>"
L"<H4>Unitary Evolution Methods</H4><P>"
L"<A NAME=\"Nash-Chen\">"
L"<H5>Nash-Chen</H5></A>"
L"<XML ID=\"XMLID6\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <times/>"
L"      <msub>"
L"         <mo>&Psi;</mo>"
L"         <ci>x</ci>"
L"      </msub>"
L"      <mfence>"
L"         <apply>"
L"            <plus/>"
L"            <ci>t</ci>"
L"            <apply>"
L"               <times/>"
L"               <mo>&delta;</mo>"
L"               <ci>t</ci>"
L"            </apply>"
L"         </apply>"
L"      </mfence>"
L"   </apply>"
L"   <apply>"
L"      <plus/>"
L"      <apply>"
L"         <times/>"
L"         <apply>"
L"            <power/>"
L"            <ci>e</ci>"
L"            <apply>"
L"               <times/>"
L"               <apply>"
L"                  <minus/>"
L"                  <ci>i</ci>"
L"               </apply>"
L"               <mo>&lambda;</mo>"
L"               <mfence>"
L"                  <apply>"
L"                     <plus/>"
L"                     <cn>1</cn>"
L"                     <msub>"
L"                        <ci>U</ci>"
L"                        <ci>x</ci>"
L"                     </msub>"
L"                  </apply>"
L"               </mfence>"
L"            </apply>"
L"         </apply>"
L"         <msub>"
L"            <ci>J</ci>"
L"            <cn>0</cn>"
L"         </msub>"
L"         <mfence>"
L"            <mo>&lambda;</mo>"
L"         </mfence>"
L"         <msub>"
L"            <mo>&Psi;</mo>"
L"            <ci>x</ci>"
L"         </msub>"
L"         <mfence>"
L"            <ci>t</ci>"
L"         </mfence>"
L"      </apply>"
L"      <apply>"
L"         <sum/>"
L"         <lowlimit>"
L"            <cn>1</cn>"
L"         </lowlimit>"
L"         <uplimit>"
L"            <mo>&infin;</mo>"
L"         </uplimit>"
L"         <bvar>"
L"            <apply>"
L"               <times/>"
L"               <ci>x</ci>"
L"               <ci>'</ci>"
L"            </apply>"
L"         </bvar>"
L"         <apply>"
L"            <times/>"
L"            <apply>"
L"               <power/>"
L"               <ci>i</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <ci>x</ci>"
L"                  <ci>'</ci>"
L"               </apply>"
L"            </apply>"
L"            <msub>"
L"               <ci>J</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <ci>x</ci>"
L"                  <ci>'</ci>"
L"               </apply>"
L"            </msub>"
L"            <mfence>"
L"               <mo>&lambda;</mo>"
L"            </mfence>"
L"            <mfence>"
L"               <apply>"
L"                  <plus/>"
L"                  <apply>"
L"                     <times/>"
L"                     <msub>"
L"                        <mo>&Psi;</mo>"
L"                        <apply>"
L"                           <minus/>"
L"                           <ci>x</ci>"
L"                           <apply>"
L"                              <times/>"
L"                              <ci>x</ci>"
L"                              <ci>'</ci>"
L"                           </apply>"
L"                        </apply>"
L"                     </msub>"
L"                     <mfence>"
L"                        <ci>t</ci>"
L"                     </mfence>"
L"                  </apply>"
L"                  <apply>"
L"                     <times/>"
L"                     <msub>"
L"                        <mo>&Psi;</mo>"
L"                        <apply>"
L"                           <plus/>"
L"                           <ci>x</ci>"
L"                           <apply>"
L"                              <times/>"
L"                              <ci>x</ci>"
L"                              <ci>'</ci>"
L"                           </apply>"
L"                        </apply>"
L"                     </msub>"
L"                     <mfence>"
L"                        <ci>t</ci>"
L"                     </mfence>"
L"                  </apply>"
L"               </apply>"
L"            </mfence>"
L"         </apply>"
L"      </apply>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"<BR>for x = 0, 1, 2, ..., N - 1, where<br> "
L"<XML ID=\"XMLID7\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <times/>"
L"      <msub>"
L"         <mo>&Psi;</mo>"
L"         <apply>"
L"            <plus/>"
L"            <ci>x</ci>"
L"            <ci>N</ci>"
L"         </apply>"
L"      </msub>"
L"      <mfence>"
L"         <apply>"
L"            <plus/>"
L"            <ci>t</ci>"
L"            <apply>"
L"               <times/>"
L"               <mo>&delta;</mo>"
L"               <ci>t</ci>"
L"            </apply>"
L"         </apply>"
L"      </mfence>"
L"   </apply>"
L"   <apply>"
L"      <times/>"
L"      <msub>"
L"         <mo>&Psi;</mo>"
L"         <ci>x</ci>"
L"      </msub>"
L"      <mfence>"
L"         <apply>"
L"            <plus/>"
L"            <ci>t</ci>"
L"            <apply>"
L"               <times/>"
L"               <mo>&delta;</mo>"
L"               <ci>t</ci>"
L"            </apply>"
L"         </apply>"
L"      </mfence>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"The J<sub>n</sub> are Bessel functions of the first kind.<BR>"
L"P. L. Nash and L.Y. Chen, Efficient finite difference solutions to the time-dependent Schrodinger"
L"equation, <em>Journal of Computational Physics</em>, <strong>130</strong>, p266 (1997)."
L"<HR>"
\
L"<A NAME=\"Cayley\"><H5>Cayley</H5></A>"
L"<XML ID=\"XMLID8\">"
L"<ea>"
L"   <reln>"
L"      <eq/>"
L"      <apply>"
L"         <times/>"
L"         <apply>"
L"            <power/>"
L"            <ci>e</ci>"
L"            <apply>"
L"               <times/>"
L"               <apply>"
L"                  <over/>"
L"                  <ci>i</ci>"
L"                  <cn>2</cn>"
L"               </apply>"
L"               <ci>H</ci>"
L"               <mo>&delta;</mo>"
L"               <ci>t</ci>"
L"            </apply>"
L"         </apply>"
L"         <mo>&Psi;</mo>"
L"         <mfence>"
L"            <apply>"
L"               <plus/>"
L"               <ci>t</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"      </apply>"
L"      <apply>"
L"         <times/>"
L"         <apply>"
L"            <power/>"
L"            <ci>e</ci>"
L"            <apply>"
L"               <times/>"
L"               <apply>"
L"                  <minus/>"
L"                  <apply>"
L"                     <over/>"
L"                     <ci>i</ci>"
L"                     <cn>2</cn>"
L"                  </apply>"
L"               </apply>"
L"               <ci>H</ci>"
L"               <mo>&delta;</mo>"
L"               <ci>t</ci>"
L"            </apply>"
L"         </apply>"
L"         <mo>&Psi;</mo>"
L"         <mfence>"
L"            <apply>"
L"               <minus/>"
L"               <ci>t</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"      </apply>"
L"   </reln>"
L"   <reln>"
L"      <eq/>"
L"      <apply>"
L"         <times/>"
L"         <mfence>"
L"            <apply>"
L"               <plus/>"
L"               <cn>1</cn>"
L"               <apply>"
L"                  <times/>"
L"                  <apply>"
L"                     <over/>"
L"                     <ci>i</ci>"
L"                     <cn>2</cn>"
L"                  </apply>"
L"                  <ci>H</ci>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"         <mo>&Psi;</mo>"
L"         <mfence>"
L"            <apply>"
L"               <plus/>"
L"               <ci>t</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"      </apply>"
L"      <apply>"
L"         <times/>"
L"         <mfence>"
L"            <apply>"
L"               <minus/>"
L"               <cn>1</cn>"
L"               <apply>"
L"                  <times/>"
L"                  <apply>"
L"                     <over/>"
L"                     <ci>i</ci>"
L"                     <cn>2</cn>"
L"                  </apply>"
L"                  <ci>H</ci>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"         <mo>&Psi;</mo>"
L"         <mfence>"
L"            <apply>"
L"               <minus/>"
L"               <ci>t</ci>"
L"               <apply>"
L"                  <times/>"
L"                  <mo>&delta;</mo>"
L"                  <ci>t</ci>"
L"               </apply>"
L"            </apply>"
L"         </mfence>"
L"      </apply>"
L"   </reln>"
L"</ea>"
L"</XML>"
L"<BR>This yields a tridiagonal system wthe previous approximation for the Laplacian"
\
L"<HR>"
\
L"<A NAME=\"PeriodicCayley\"><H5>Periodic Cayley</H5></A>"
L"The tridiagonal Cayley system plus two additional matrix elements in "
L"the coefficient matrix at locations (first row, last column) and"
L"(last row, first column). This generates a sparse system that"
L"cannot be solved as efficiently as the tridiagonal system. "
L"The solution is periodic."
L"When possible, it is more efficient to place potential barriers on the "
L"left and right boundaries and use the Cayley tridiagonal system.<BR>"
\
\
\
L"</BODY>"
L"</HTML>";

///////////////////////////////////////////////////////////////////////////////

const _bstr_t bstrSuperposition2 =
L"<HTML>"
L"<HEAD>"
L"<TITLE>Investigation of Particle Waves</TITLE>"
L"</HEAD>"
L"<BODY>"
L"Relative Probability Density of a Free Particle in Spacetime"
L"<HR>"
L"The red horizontal axis is the x-axis.<br>"
L"The blue axis normal to the screen is the time axis.<br>"
L"The green vertical axis is the quantum mechanical relative probability density.<P>"
L"Drag with the left mouse button down to rotate the view.<BR>"
L"Drag with the right mouse button down to zoom.<BR>"
L"<HR>"
L"Wavefunction:<BR>"
L"<XML ID=\"XMLID1\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <times/>"
L"      <mo>&Psi;</mo>"
L"      <mfence>"
L"         <ci>x</ci>"
L"         <ci>t</ci>"
L"      </mfence>"
L"   </apply>"
L"   <apply>"
L"      <sum/>"
L"      <lowlimit>"
L"      </lowlimit>"
L"      <bvar>"
L"         <ci>k</ci>"
L"      </bvar>"
L"      <apply>"
L"         <times/>"
L"         <msub>"
L"            <ci>A</ci>"
L"            <ci>k</ci>"
L"         </msub>"
L"         <apply>"
L"            <power/>"
L"            <ci>e</ci>"
L"            <apply>"
L"               <minus/>"
L"               <apply>"
L"                  <times/>"
L"                  <ci>i</ci>"
L"                  <ci>k</ci>"
L"                  <ci>x</ci>"
L"               </apply>"
L"               <apply>"
L"                  <over/>"
L"                  <apply>"
L"                     <times/>"
L"                     <ci>i</ci>"
L"                     <apply>"
L"                        <power/>"
L"                        <ci>k</ci>"
L"                        <cn>2</cn>"
L"                     </apply>"
L"                     <ci>t</ci>"
L"                  </apply>"
L"                  <cn>2</cn>"
L"               </apply>"
L"            </apply>"
L"         </apply>"
L"      </apply>"
L"   </apply>"
L"</reln>"
L"</XML>"
L"<BR>where  "
L"<XML ID=\"XMLID2\">"
L"<reln>"
L"   <eq/>"
L"   <msub>"
L"      <ci>A</ci>"
L"      <ci>k</ci>"
L"   </msub>"
L"   <ea>"
L"      <apply>"
L"         <cn>0</cn>"
L"      </apply>"
L"      <apply>"
L"         <cn>1</cn>"
L"      </apply>"
L"   </ea>"
L"</reln>"
L"</XML>"
L"<BR>and  "
L"<XML ID=\"XMLID3\">"
L"<reln>"
L"   <eq/>"
L"   <apply>"
L"      <over/>"
L"      <ci>h</ci>"
L"      <apply>"
L"         <times/>"
L"         <cn>2</cn>"
L"         <mo>&pi;</mo>"
L"      </apply>"
L"   </apply>"
L"   <cn>1</cn>"
L"   <ci>particle mass</ci>"
L"</reln>"
L"</XML>"
L"</BODY></html>";

///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
const _bstr_t bstrLogisticMap2 =
L"<HTML>"
L"<HEAD>"
L"<TITLE>Logistic Map, Copyright 2000, Dr. P.L. Nash</TITLE>"
L"</HEAD>"
L"<BODY>"
L"<H4>Logistic Map</h4>"
L"<HR>"
L"<ea>"
L"   <reln>"
L"      <eq/>"
L"      <msub>"
L"         <ci>x</ci>"
L"         <apply>"
L"            <plus/>"
L"            <ci>n</ci>"
L"            <cn>1</cn>"
L"         </apply>"
L"      </msub>"
L"      <apply>"
L"         <times/>"
L"         <ci>R</ci>"
L"         <msub>"
L"            <ci>x</ci>"
L"            <ci>n</ci>"
L"         </msub>"
L"         <mfence>"
L"            <apply>"
L"               <minus/>"
L"               <cn>1</cn>"
L"               <msub>"
L"                  <ci>x</ci>"
L"                  <ci>n</ci>"
L"               </msub>"
L"            </apply>"
L"         </mfence>"
L"      </apply>"
L"   </reln>"
L"   <apply>"
L"      <times/>"
L"      <ci>w</ci>"
L"      <ci>h</ci>"
L"      <ci>e</ci>"
L"      <ci>r</ci>"
L"      <ci>e</ci>"
L"   </apply>"
L"   <reln>"
L"      <leq/>"
L"      <cn>0</cn>"
L"      <ci>R</ci>"
L"      <cn>4</cn>"
L"   </reln>"
L"   <reln>"
L"      <leq/>"
L"      <cn>0</cn>"
L"      <msub>"
L"         <ci>x</ci>"
L"         <ci>n</ci>"
L"      </msub>"
L"      <cn>1</cn>"
L"   </reln>"
L"</ea>"
L"<P>The Logistic Map birth rate 'R' is the vertical coordinate.<P>"
L"<P>The Logistic Map population x<sub>n</sub> is the horizontal coordinate.<P>"
L"<HR>"
L"<h4>Press the ESCAPE key to quit this example.</h4><hr>"
L"**Important**<p>"
L"The function of the arrow keys has changed from the default behavior.<P>"
L"<P>"
L"Definitions:"
L"<ul>"
L"<li>VK_HOME   =     'Home' key"
L"<li>VK_END    =     'End' key"
L"<li>VK_PRIOR   =     'Page Up' key"
L"<li>VK_NEXT    =     'Page Down' key"
L"<li>VK_TAB    =     'Tab' key"
L"<li>VK_LEFT   =     'Left' arrow key"
L"<li>VK_RIGHT  =     'Right' arrow key"
L"<li>VK_UP     =     'Up' arrow key"
L"<li>VK_DOWN   =     'Down' arrow key"
L"<li>bShift    =     'Shift' key is pressed"
L"<li>bCtrl     =     'Ctrl' key is pressed"
L"<li>g_Rate    =     Logistic Map birth rate 'R'"
L"<li>inc       =     \"g_Rate increases by\""
L"<li>dec       =     \"g_Rate decreases by\""
L"</ul>"
L"<P>"
L"Actions:"
L"<ul>"
L"<li>VK_HOME =>     g_Rate = 1"
L"<li>VK_END =>      g_Rate = 4"
L"<li>VK_LEFT bShift bCtrl =>     dec 0.0001"
L"<li>VK_LEFT bShift  =>     dec 0.001"
L"<li>VK_LEFT  bCtrl =>     dec 0.01"
L"<li>VK_LEFT  =>     dec 0.1"
L"<li>VK_RIGHT bShift bCtrl =>     inc 0.0001"
L"<li>VK_RIGHT bShift  =>     inc 0.001"
L"<li>VK_RIGHT  bCtrl =>     inc 0.01"
L"<li>VK_RIGHT  =>     inc 0.1"
L"<li>VK_UP bShift bCtrl =>     inc 0.00001"
L"<li>VK_UP bShift  =>     shift plot to right by 0.1"
L"<li>VK_UP  bCtrl =>     shift plot vertically up by 0.1"
L"<li>VK_UP  =>     zoom in by 0.1"
L"<li>VK_DOWN bShift bCtrl =>     dec 0.00001"
L"<li>VK_DOWN bShift  =>     shift plot to left by 0.1"
L"<li>VK_DOWN  bCtrl =>     shift plot vertically down by 0.1"
L"<li>VK_DOWN  =>     zoom out by 0.1"
L"<li>VK_PRIOR  =>     zoom in by 1"
L"<li>VK_NEXT  =>     zoom out by 1"
L"<li>VK_TAB  bCtrl =>     slow down 'play'"
L"<li>VK_TAB  =>     speed up 'play'"
L"</ul>"
L"<P><H5>Author: Dr. P.L. Nash</h5>"
L"</BODY></html>";

///////////////////////////////////////////////////////////////////////////////
const _bstr_t bstrs[] = {
	bstrStartUp,
	bstrLogisticMap,
	bstrQM_2DScatt,
	bstrQM_1DScatt,
	bstrSuperposition,
	bstrElectroStatics,
	bstrCurrentLoop,
	bstrQM_2DScatt2,
	bstrQM_1DScatt2,
	bstrSuperposition2,
	bstrLogisticMap2
};
///////////////////////////////////////////////////////////////////////////////

#endif
